### PR TITLE
Fix language fallback

### LINKED ISSUE #58: [Bug]: Language fallback no longer working
### What did you expect? 🧐

An undefined language should result in the announcement using the provided fallback.

### What actually happened? 😵‍💫

No announcement is made if the language is not defined in the options. This started happening in 4.5.1, specifically after [this pull request](https://github.com/swup/a11y-plugin/pull/46) was merged. The part that seemed redundant was actually the relevant implementation of the fallback: `announcements['*']`.

I'll make a note to fix and test this in the test branch that's currently in progress, just flagging it here so we don't forget.

### Swup and plugin versions 📝

- swup: *
- a11y plugin: 4.5.1

### What browsers are you seeing the problem on? 🧭

_No response_

### Relevant log output 🤓

_No response_

### URL to minimal reproduction 🔗

https://github.com/swup/a11y-plugin/pull/46/files

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Correctly fall back to the missing-language announcement templates
- Nice to publish this as a last patch release
- Includes version bump and changelog entry

**Question**

- How do we merge & publish this? The `master` branch already has the next major release in it
- Should have created a `next` branch like before 😭
- Probably we need to create a tag on the `version/automated` branch, and release from that tag

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [ ] ~~All tests are passing (`npm run test`)~~
- [ ] ~~New or updated tests are included~~
- [ ] ~~The documentation was updated as required~~

**Additional information**

Closes #58

### CODE REVIEW

**Review by hirasso — APPROVED** [review]
Just to make sure I understand: Is this meant for setups where the html tag has a `lang` attribute but the value of that attribute doesn't have an equivalent in the `AnnouncementTranslations` object?

**Comment by hirasso** [comment]
> - Probably we need to create a tag on the version/automated branch, and release from that tag

😵‍💫 this is once again beyond my knowledge of Git... I'll trust you to find the ideal way. I'd probably create a next branch right after #46 was merged, reset the master branch to that commit and force-push.

**Comment by daun** [comment]
@hirasso Exactly! The first `*` was for the case of a missing `lang` attribute, the second `*` was for the case of a missing entry in the announcements object.

**Comment by daun** [comment]
@hirasso I like force-pushing! Let me check if we can disable the branch protection rules for a minute and do that here.

**Comment by daun** [comment]
@hirasso Force-pushing saved the day! Had to enable and then disable it again, but no problems otherwise.

**Pull request merged**
