### PR TITLE
Feature/aria busy attribute

### PR DESCRIPTION
**Pull request by hirasso**
As [discussed here](https://github.com/swup/swup/issues/466). I also ported the new linting behavior from the swup main repo. Hope it's ok to have put both the new feature and the linting things in one PR 😅

### CODE REVIEW

**Comment by daun** [comment]
Feature looks good! Adding prettier here is fine, but I think we should keep the build script as is for now until we've converged on a way to handle it.

**Comment by daun** [comment]
Did you run `npm update` with this one? So we can get rid of the dependabot PRs 🤠

**Comment by hirasso** [comment]
Can I not merge here? It says that you approved but there is no merge button

**Comment by daun** [comment]
Yeah, that's because the PR is from your fork and not a feature branch of this repo. Silly but has a certain logic. I'll merge.

**Comment by hirasso** [comment]
Ok, I'll start creating PRs directly from the main repos.

**Pull request merged**
