### PR TITLE
Allow overriding focus selector

### LINKED ISSUE #26: Allow dynamic focus target
**Describe the problem**

- Some visits don't need to reset focus to the `main` element, e.g. fragment visits like filter UIs
- Ideally, the custom focus target could be overwritten per visit
- The fragment plugin and users can then just set `visit.focus = '#list'` or similar

**Describe the proposed solution**

- New key in visit object: `visit.focus` — or maybe nested/grouped somewhere?
- New hook `content:focus` that can be replaced

**How important is this feature to you?**

- [ ] Nice to have
- [x] Would make my life a lot easier
- [ ] I cannot use swup without it

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Allow focussing different elements per visit, e.g. for fragment visits
- Create a new `visit.a11y.focus` key that holds a selector or element to be focused
- Create `content:focus` hook to allow delaying or replacing the focus logic
- Only add `tabindex="-1"` where required to allow focussing via JS
- Tested in playground

**Visit object**

```js
{
  from: {},
  to: {},
  a11y: {
    focus: 'main'
  }
}
```

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] The documentation was updated as required

**Additional information**

Closes #26

### CODE REVIEW

**Comment by daun** [comment]
@hirasso Would love to know your opinion on where to put this in the visit object — root-level `focus` key or nested in a separate `content` parent key? Or something else entirely? `a11y`?

**Comment by hirasso** [comment]
How about grouping the flags under `visit.a11y`?

**Comment by hirasso** [comment]
Ah yes, just saw that you already suggested `a11y` in your comment. I like that!

**Comment by daun** [comment]
Ready for review :) Moved everything into `a11y` and allowed setting focus by passing HTML elements directly.

**Comment by hirasso** [comment]
Nice! What's the use case for passing in an HTMLElement to be focused? I can imagine that this could confuse users if they don't have a clear concept of how swup works. They might pass the element too early (on `visit:start` for example) and then the element could be gone already when it should be focused.

**Comment by daun** [comment]
@hirasso The use case is mostly for inline forms — if there's multiple forms on the same page, the best option I could think of for focussing the form itself was to grab `visit.trigger.el` directly — generating a string selector from the element's id might work but isn't very elegant. But maybe there's a better way of doing this?

If we decide to leave this in, I'm happy to add a note about hooking right before `content:focus` for it to work correctly.

**Comment by hirasso** [comment]
Yes, the note sounds good!

**Comment by daun** [comment]
Added a readme section on the extended visit object and a note on passing in actual element instances.

**Comment by hirasso** [comment]
How about detecting `content:replace` and throwing an error if `a11y.focus` was set to an element before this hook?

**Comment by daun** [comment]
@hirasso I'd rather remove the possibility entirely, then. Actually, let's do that. We're not putting any elements into the visit object, ever, except for the trigger element itself. More consistent. I'll just need to work around it by setting IDs on elements — the form plugin requires IDs on forms, anyway.

**Comment by daun** [comment]
Changed to only allow selector strings. I like it much better now, actually, thanks for insisting it's not such a good idea!

**Review by hirasso — APPROVED** [review]

**Pull request merged**
